package com.variance.msora.util;

/**
 * Please adhere to the addition of new parameter rules! Always update this
 * value of next id to use. Next ID (1052)
 * 
 * @author marembo
 * 
 */
public enum ActionParameterValue {
	BUSINESS_CONTACTS_LOAD(0x1001), BUSINESS_CONTACTS_CHECK_USER_MEMBERSHIP(
			0x1002), BUSINESS_CONTACTS_NEW(0x1003), BUSINESS_CONTACTS_ADD_FROM_PERSONAL_CONTACTS(
			0x1004), BUSINESS_CONTACTS_ADD_NEW_CONTACT(0x1005), BUSINESS_CONTACTS_ADD_USER(
			0x1006), BUSINESS_CONTACTS_REMOVE_USER(0x1007), BUSINESS_CONTACTS_SELECT_USER(
			0x1008), BUSINESS_CONTACTS_COUNTS(0x1009), PERSONAL_CONTACTS_LOAD_CONTACTS_FOR_BUSINESS_SELECTION(
			0x1010), PERSONAL_CONTACTS_COUNTS(0x1011), LIVELINK_DOWNLOAD(0x1012), LIVELINK_CONTACT(
			0x1013), LIVELINK_REQUEST(0x1014), LIVELINK_REQUEST_FIND_CONTACTS_ON_Msora(
			0x1015), LIVELINK_REQUEST_FIND_CONTACTS_NOT_ON_Msora(0x1016), LIVELINK_REQUEST_LINK_TO_CONTACTS_ON_Msora(
			0x1017), msora_ANDROID_PARAMETER(0x1018), msora_ANDROID_STATUS(
			0x1019), LIVELINK_AVAILABLE(0x1020), msora_CURRENT_INTERNATIONAL_DIALING_CODE(
			0x1021), msora_SHARE_CONTACT(0x1022), msora_SHARE_PROFILE_BUSINESS_CARD(
			0x1023), CORPORATE_CONTACT_DETAILS(0x1024), msora_GCM_KEY_REGISTERED(
			0x1026), PERSONAL_CONTACTS_SEARCH(0x1027), PERSONAL_CONTACTS_LOAD_ALL(
			0x1028), PERSONAL_CONTACT_BACKUP_STARTED(0x1030), PERSONAL_CONTACT_BACKUP_COMPLETE(
			0x1031), PERSONAL_CONTACT_DELETE_CONTACTS(0x1032), PERSONAL_CONTACT_SYNC(
			0x1033), msora_LOGIN_REQUEST(0x1034), LIVELINK_MYLIVELINKS(
			0x1035), LIVELINK_REVOKE_MYLIVELINKS(0x1036), AD_REQUEST(0x1037), DISCOVERY_SEARCH_CONTACTS(
			0x1038), PERSONAL_CONTACT_FIND(0x1039), LIVELINKED_CONTACT_ONLINE(
			0x1040), LIVELINKED_CONTACT_CHAT_REQUEST(0x1041), BUSINESS_CONTACTS_LOAD_CONTACTS_FOR_SELECTION(
			0x1042), CORPORATE_CONTACTS_LOAD_CONTACTS_FOR_SELECTION(0x1043), BUSINESS_SEND_BULK_MESSAGE(
			0x1044), BUSINESS_MEETING_FIND_MEETING(0x1045), BUSINESS_MEETING_JOIN_MEETING(
			0x1046), BUSINESS_MEETING_SCHEDULE_MEETING(0x1047), BUSINESS_MEETING_CLOSE_MEETING(
			0x1048), BUSINESS_MEETING_SUSPEND_MEETING(0x1048), BUSINESS_MEETING_START_MEETING(
			0x1049), BUSINESS_MEETING_LEAVE_MEETING(0x1050), BUSINESS_MEETING_SAVE_BUSINESS_CARD(
			0x1051);
	private int valueId;

	private ActionParameterValue(int valueId) {
		this.valueId = valueId;
	}

	public static ActionParameterValue valueOf(int valueId) {
		for (ActionParameterValue a : values()) {
			if (a.valueId == valueId) {
				return a;
			}
		}
		return null;
	}

	@Override
	public String toString() {
		return valueId + "";
	}
}
